services:
  config-service:
    container_name: config-service
    build:
      context: .
      target: final
    environment:
      - SERVE_PORT=8080
    ports:
      - "8080:8080"
    network_mode: bridge
    restart: unless-stopped
